<script>
    const randomlines = [
        ' kinda crap.',
        ' a pyramid scheme.',
        ' not good for anything!',
        ' low-tier.',
        ' an airbrush abuser.',
        ' not doing what they should be doing.',
        ' jumping into light fierce.',
        ' punishable on hit.',
        ' in the mines.',
        ' caffeine-crashed.',
        ' dead on arrival.',
        "n't.",
        ' drawing catgirls!',
        ' feeding the cows.',
        ' nothing but a concept.',
        ' in a second-hand store near you!',
        ' broke as hell.',
        ' spending too much money on gas.',
        ' guilty.',
        ' in training mode.',
        ' eating slop.',
        ' a Bolivian 17-year old IT worker.',
        ' the owner of a PS5 game.',
        ' a trans ally!',
        ' banned from this arcade.',
        ' anemic.',
        ' single and ready to fumble!',
        ' not even a real pillow!',
        ' John.',
        ' sauceless and cringe!',
        ' a type of herb.',
        ' not behind you at the moment.',
        ' spinning to win!',
        ' dependent on proprietary software.',
        ' probably bi.',
        ' SAND BLAST',
        ' screaming very loudly.',
        ' contrary to popular belief, an artist.',
        ' not affiliated with anything car-related.',
        ' selling land on the moon!',
        ' a portable machine gun!',
        ' this god damn close to installing Linux.',
        ' watching the newest season of a TV show.',
        ' built for rough conditions!',
        ' a fighting game player!',
        ' grateful for your help!',
        ' a single parent of 20.',
        ' unaware of the existence of gradient maps.',
        ' bad at Blender.',
        ' that guy.',
        ' horrible at posting.',
        ' lowballing you on Grailed.',
        ' drawing your OC! like, right now!',
        ' nice to small cats and kitties.',
        ' coming to Brasil!',
        ' coming to the Philips CD-i!',
        ' coming to all systems in your possession!',
        ' wishing for an operating system that works good.',
        ' playing Balatro instead of doing anything useful.',
        ' supporting their locals! Are you?',
        ' not on Twitter! Or X! Or whatever it\'s called!',
        ' picking stuff up and putting it elsewhere.',
        ' buying another god forsaken sketchbook again.',
        ' playing OldSchool RuneScape! Help!',
        ' working on commissions i swear',
        ' Atkinson Hyperlegibles strongest warrior.',
    
        ' using Astro!',
        ' using Clip Studio Paint!',
        ' using DaVinci Resolve!',
        ' using an XP-Pen Artist 24 Pro!',
        ' using a Keychron V4!',
        ' using a Haute42 leverless!',
        ' using Windows Terminal!',
        ' using Kdenlive!',
        ' using PureRef!', 
        ' using Obsidian!',
        ' using LibreOffice!',
        ' using ShareX!',
        ' using Mozilla Thunderbird!',
        ' using Voidtools Everything!',
        ' using Mozilla Firefox!',
        ' using Zen Browser!',
        ' using git!',
        ' using GitHub Pages!',
        ' using Bitwarden!',
        ' using fish-shell!',
        ' using zoxide!',
        ' using JetBrains IDEs!',
        ' using 7-Zip!',
        ' using VoiceMeeter Banana!',
        ' using VLC Media Player!',
        ' using Windhawk!',
        ' using i3wm!'
    ]
</script>

{randomlines[Math.floor(Math.random()*randomlines.length)]}